name: C++ CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake and googletest
        run: sudo apt install -y cmake libgmock-dev
      - name: configure
        run: ./configure && ./configure
      - name: make
        run: make
        working-directory: build
      - name: tests
        run: make tests
        working-directory: build
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake
        run: sudo apt install -y cmake
      - name: configure
        run: ./configure && ./configure
      - name: check
        run: make check-all
        working-directory: build
