name: C++ Compilation and Test

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake and googletest
        run: sudo apt install -y cmake libgmock-dev
      - name: configure
        run: ./configure && ./configure
      - name: make
        run: make
        working-directory: build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: tests
        run: make tests
        working-directory: build
